### ISSUE TITLE
Can't login. 

### ISSUE THREAD

**Issue by hgk8769789** [ading2210/openai-key-scraper#1]
I put my cookie in the command but I am getting this error while running, how do I fix this?

Searching with query: sk- openai
Checking page 1...
Replit returned an error. Retrying in 5 seconds...
Unauthorized, please log in.
Replit returned an error. Retrying in 5 seconds...
Unauthorized, please log in.

**Comment by BoghosDavtyan** [comment]
Did you close this because you solve this? how did you solve this?

**Comment by vaibhavard** [comment]
Yes Same error..How to solve?
